name: Debian 9 Stretch
on:
  repository_dispatch:
    types:
    - 'debian-9'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y libguestfs-tools ;\
        echo;

    - name: Code Checkout
      uses: actions/checkout@v2.3.4

    - name: Prepare Debian Stretch 9 Image
      run: |
        set -ex ;\
        curl --output /tmp/debian.qcow2 -L "https://cdimage.debian.org/images/cloud/OpenStack/current-9/debian-9-openstack-amd64.qcow2" ;\
        qemu-img resize /tmp/debian.qcow2 +22G ;\
        sudo virt-sysprep -a /tmp/debian.qcow2 --password debian:password:debian ;\
        sudo virt-customize -a /tmp/debian.qcow2 --install 'curl,tmux,git,vim,net-tools,qemu-guest-agent,cloud-init,cloud-initramfs-growroot' ;\
        sudo virt-customize -a /tmp/debian.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/debian.qcow2 --update ;\
        echo;

    - name: Build Debian Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/debian --image-tag 9 --image-file /tmp/debian.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Debian Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/debian:9 ;\
        podman push quay.io/containercraft/debian:9 docker://quay.io/containercraft/debian:stretch ;\
        podman image prune --all --force ;\
        echo;
